server:
  port: 50001
spring:
  application:
    name: app-001-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]': # 匹配所有请求
            allowedHeaders: "*" # 跨域处理 允许所有的域
            allowedOrigins: "*" # 支持的方法
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTION
      routes:
        # 平台管理
        - id: user
          uri: lb://app-001-user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix= 1

