server:
  port: 10240

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/app-001-file?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
  application:
    name: fileService

mybatis-plus:
  # Mapper 所对应的 XML 文件位置
  mapper-locations: classpath:mapper/**/*.xml
  global-config:
    db-config:
      # 逻辑删除已删除值
      logic-delete-value: 1
      # 逻辑删除未删除值
      logic-not-delete-value: 0
      # 全局的 entity 的逻辑删除字段属性名,(逻辑删除下有效)
      logic-delete-field: deleted
  configuration:
    # 是否开启自动驼峰命名规则
    map-underscore-to-camel-case: true
    # 关闭 Mybatis 二级缓存，默认为 true
    cache-enabled: false
    # XXXXXXX
    call-setters-on-nulls: true

minio:
  endpoint: http://127.0.0.1:9000
  access-key: minioadmin
  access-secret: minioadmin
  bucket: files
